# Generated by Django 5.2.3 on 2025-06-25 20:13

import autoslug.fields
import django.db.models.deletion
from slugify import slugify  # <-- এখানে পরিবর্তন
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=slugify, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=slugify, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('poster', models.URLField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('language', models.TextField(blank=True, max_length=100, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('genre', models.ManyToManyField(to='movie_app.genre')),
            ],
            options={
                'ordering': ('-release_date',),
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='get_username', slugify=slugify, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar', models.ImageField(default='default-avatar/default-avatar.webp', upload_to='user-avatars/')),
                ('info', models.TextField()),
                ('instagram', models.CharField(blank=True, max_length=1024, null=True)),
                ('twitter', models.CharField(blank=True, max_length=1024, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
